apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    app: mysite
spec:
  volumes:
  - name: db
    persistentVolumeClaim:
      claimName: db
  containers:
  - name: mysite
    image: ghcr.io/25542554/cis-92-mac:main
    imagePullPolicy: Always
    volumeMounts:
    - name: db
      mountPath: /db
    resources:
      limits:
        cpu: 256m 
        memory: 250Mi
    livenessProbe:
      httpGet:
        path: /polls/
        port: 8000
    ports:
    - containerPort: 8000
    env:
    - name: DB_ENGINE
      value: "postgres"
    - name: DB_NAME
      value: "mysite"
    - name: DB_USER
      value: "postgres"
    - name: DB_HOST
      value: "postgres"
    - name: DB_PASSWORD
      value: "django"
    - name: DJANGO_ADMIN_EMAIL
      value: "dennis@dennis.com"
    - name: DJANGO_ADMIN_USERNAME
      value: "dennis"
    - name: DJANGO_SUPERUSER_PASSWORD
      value: "dennis"