apiVersion: v1
kind: Pod
metadata:
  name: mysitemac
  labels:
    app: mysitemac
spec:
  containers:
  - name: mysitemac
    image: ghcr.io/25542554/cis-92-mac:main
    imagePullPolicy: Always
    ports:
    - containerPort: 8000
    env:
    - name: DB_ENGINE
      value: "sqlite"
    - name: DJANGO_ADMIN_EMAIL
      value: "test@test.test"
    - name: DJANGO_ADMIN_USERNAME
      value: "test"
    - name: DJANGO_SUPERUSER_PASSWORD
      value: "test"